import 'cloud_sync_shadow_report_file.dart';
import 'cloud_sync_models.dart';
import 'cloud_sync_semantic_pull_report_file.dart';
import 'cloudkit_operation_interlock.dart';
import 'cloudkit_writer_authority.dart';

const _cloudSyncV2SafeFailureCodes = <String>{
  'account_changed',
  'account_unavailable',
  'cloud_sync_outbound_canary_active',
  'cloud_sync_outbound_canary_admission_invalid',
  'cloud_sync_outbound_canary_already_armed',
  'cloud_sync_outbound_canary_confirmation_expired',
  'cloud_sync_outbound_canary_confirmation_invalid',
  'cloud_sync_outbound_canary_disabled',
  'cloud_sync_outbound_canary_message_time_invalid',
  'cloud_sync_outbound_canary_outbox_invalid',
  'cloud_sync_outbound_canary_postflight_invalid',
  'cloud_sync_outbound_canary_quiescing',
  'cloud_sync_outbound_canary_recovery_invalid',
  'cloud_sync_outbound_canary_tripwire',
  'cloud_sync_outbound_canary_unavailable',
  'cloud_sync_outbound_canary_writer_disabled',
  'cloud_sync_outbound_candidate_selection_failed',
  'cloud_sync_outbound_quiescence_timeout',
  'cloud_sync_developer_mode_required',
  'cloud_sync_canary_package_required',
  'cloud_sync_native_auth_account_fingerprint_failed',
  'cloud_sync_native_auth_account_changed',
  'cloud_sync_native_auth_account_unavailable',
  'cloud_sync_native_auth_bridge_failed',
  'cloud_sync_native_auth_client_type_invalid',
  'cloud_sync_native_auth_identity_mismatch',
  'cloud_sync_native_auth_metadata_invalid',
  'cloud_sync_native_auth_session_fingerprint_failed',
  'cloud_sync_native_auth_storage_invalid',
  'cloud_sync_native_auth_store_identity_failed',
  'cloud_sync_native_auth_warm_failed',
  'cloud_sync_native_auth_warm_timeout',
  'cloud_sync_native_writer_pause_already_active',
  'cloud_sync_native_writer_pause_bridge_failed',
  'cloud_sync_native_writer_pause_failed',
  'cloud_sync_native_writer_pause_timeout',
  'cloud_sync_native_writer_pause_token_invalid',
  'cloud_sync_native_writer_resume_failed',
  'cloud_sync_native_writer_resume_token_invalid',
  'cloud_sync_private_storage_unavailable',
  'cloud_sync_protocol_evidence_architecture_invalid',
  'cloud_sync_protocol_evidence_attempt_invalid',
  'cloud_sync_protocol_evidence_build_commit_invalid',
  'cloud_sync_protocol_evidence_count_invalid',
  'cloud_sync_protocol_evidence_directory_unavailable',
  'cloud_sync_protocol_evidence_directory_unsafe',
  'cloud_sync_protocol_evidence_elapsed_ms_invalid',
  'cloud_sync_protocol_evidence_estimated_bytes_invalid',
  'cloud_sync_protocol_evidence_event_invalid',
  'cloud_sync_protocol_evidence_event_type_invalid',
  'cloud_sync_protocol_evidence_failure_invalid',
  'cloud_sync_protocol_evidence_file_corrupt',
  'cloud_sync_protocol_evidence_journal_block_invalid',
  'cloud_sync_protocol_evidence_line_too_large',
  'cloud_sync_protocol_evidence_owned_file_invalid',
  'cloud_sync_protocol_evidence_path_escape',
  'cloud_sync_protocol_evidence_platform_invalid',
  'cloud_sync_protocol_evidence_retention_failed',
  'cloud_sync_protocol_evidence_skip_invalid',
  'cloud_sync_protocol_evidence_stream_invalid',
  'cloud_sync_protocol_evidence_timestamp_invalid',
  'cloud_sync_protocol_evidence_trigger_invalid',
  'cloud_sync_protocol_evidence_trusted_root_invalid',
  'cloud_sync_protocol_evidence_unknown_failure',
  'cloud_sync_protocol_evidence_write_failed',
  'cloud_sync_protocol_evidence_zone_invalid',
  'cloud_sync_report_already_exists',
  'cloud_sync_report_contract_invalid',
  'cloud_sync_report_directory_changed',
  'cloud_sync_report_directory_unavailable',
  'cloud_sync_report_directory_unsafe',
  'cloud_sync_report_path_invalid',
  'cloud_sync_report_retention_failed',
  'cloud_sync_report_run_id_invalid',
  'cloud_sync_report_metadata_invalid',
  'cloud_sync_report_read_only_invariant_invalid',
  'cloud_sync_report_storage_unavailable',
  'cloud_sync_report_too_large',
  'cloud_sync_report_write_failed',
  'cloud_sync_report_zone_bytes_invalid',
  'cloud_sync_report_zone_count_invalid',
  'cloud_sync_report_zone_counter_invalid',
  'cloud_sync_report_zone_elapsed_invalid',
  'cloud_sync_report_zone_label_invalid',
  'cloud_sync_sampler_active',
  'cloud_sync_sampler_disabled',
  'cloud_sync_semantic_pull_active',
  'cloud_sync_semantic_pull_disabled',
  'cloud_sync_semantic_pull_quiescing',
  'cloud_sync_semantic_pull_quiescence_timeout',
  'cloud_sync_semantic_report_already_exists',
  'cloud_sync_semantic_report_directory_invalid',
  'cloud_sync_semantic_report_directory_unavailable',
  'cloud_sync_semantic_report_directory_untrusted',
  'cloud_sync_semantic_report_metadata_invalid',
  'cloud_sync_semantic_report_read_only_invariant_invalid',
  'cloud_sync_semantic_report_storage_unavailable',
  'cloud_sync_semantic_report_too_large',
  'cloud_sync_semantic_report_write_failed',
  'cloud_sync_semantic_report_zone_count_invalid',
  'cloud_sync_semantic_report_zone_invalid',
  'cloud_sync_semantic_remote_write_tripwire',
  'cloudkit-authorization',
  'cloudkit-change-token-expired',
  'cloudkit-conflict',
  'cloudkit-continuation-no-progress',
  'cloudkit-permanent',
  'cloudkit-reset-required',
  'cloudkit-server',
  'cloudkit-throttled',
  'cloudkit-unknown',
  'cloud_sync_shadow_controller_active',
  'cloud_sync_shadow_controller_disposed',
  'cloud_sync_shadow_auth_prepare_failed',
  'cloud_sync_shadow_auth_revalidation_failed',
  'cloud_sync_shadow_cleanup_failed',
  'cloud_sync_shadow_observer_flush_failed',
  'cloud_sync_shadow_observer_open_failed',
  'cloud_sync_shadow_preflight_read_failed',
  'cloud_sync_shadow_quiescence_failed',
  'cloud_sync_shadow_store_open_failed',
  'cloud_sync_shadow_synchronize_failed',
  'cloud_sync_shadow_transport_open_failed',
  'cloud_sync_shadow_owner_disposed',
  'cloud_sync_shadow_owner_quiescing',
  'cloud_sync_shadow_owner_superseded',
  'cloud_sync_shadow_write_tripwire',
  'cloudkit_interlock_busy',
  'cloudkit_interlock_fence_lost',
  'cloudkit_interlock_mode_violation',
  'cloudkit_interlock_profile_mismatch',
  'cloudkit_interlock_required',
  'cloudkit_interlock_storage_unavailable',
  'cloudkit_interlock_unavailable',
  'canonical_attachment_owner_unavailable',
  'canonical_message_chat_unavailable',
  'canonical_message_reply_parent_unavailable',
  'canonical_reaction_parent_unavailable',
  'checkpoint_pending_page_unresolved',
  'fetch_timeout',
  'generation_mismatch',
  'http-authorization',
  'http-server',
  'http-throttled',
  'http-timeout',
  'http-unknown',
  'cloudkit_writer_authority_requires_manual_recovery',
  'cloudkit_writer_build_owner_mismatch',
  'cloudkit_writer_identity_changed',
  'cloudkit_writer_identity_revalidation_failed',
  'cloudkit_writer_legacy_queue_quarantine_failed',
  'cloudkit_writer_migration_commit_precondition_failed',
  'cloudkit_writer_provisioning_measurements_invalid',
  'cloudkit_writer_provisioning_probe_failed',
  'cloudkit_writer_transition_evidence_incomplete',
  'cloudkit_writer_transition_evidence_untrusted',
  'cloudkit_writer_transition_precondition_failed',
  'cloudkit_writer_v2_readback_failed',
  'cloudkit_writer_v2_restore_precondition_failed',
  'coordinator_active',
  'legacy_sync_active',
  'legacy_cloudkit_blocked_by_v2_writer',
  'logout_active',
  'not_ui_isolate',
  'objectbox_not_ready',
  'outbox_not_empty',
  'local-storage',
  'malformed-response',
  'messages_cloud_tombstone_projection_unavailable',
  'network',
  'pcs-unavailable',
  'protector_unavailable',
  'preflight_invalid_change_shape',
  'preflight_malformed_metadata',
  'preflight_oversized_record',
  'preflight_unknown',
  'preflight_unsupported_record_type',
  'retained_projection_authorization_changed',
  'retained_projection_incomplete',
  'rustpush_not_ready',
  'semantic_parent_missing',
  'storage_unavailable',
  'unsupported_cloud_zone',
  'unsupported_platform',
  'unknown',
};

/// Returns only a fixed diagnostic code safe for logs and user-visible copy.
///
/// Exception text is never forwarded. Unknown or newly introduced failures
/// collapse to one generic code until they receive an explicit review.
String cloudSyncV2SafeFailureCode(Object error) {
  final String? candidate = switch (error) {
    CloudSyncShadowReportFileException() => error.safeCode,
    CloudSyncSemanticPullReportFileException() => error.safeCode,
    CloudSyncFailure() => error.safeCode,
    CloudKitOperationInterlockException() => error.safeCode,
    CloudKitWriterAuthorityFailure() => error.safeCode,
    StateError() => error.message.toString(),
    _ => null,
  };
  return cloudSyncV2SafeFailureCodeForCandidate(candidate);
}

/// Returns an allowlisted diagnostic code for a known failure value.
///
/// This is intentionally closed: a syntactically valid string is not enough
/// to reach a persisted report, log, or user-visible surface.
String cloudSyncV2SafeFailureCodeForCandidate(String? candidate) =>
    _cloudSyncV2SafeFailureCodes.contains(candidate)
    ? candidate!
    : 'cloud_sync_unknown_failure';
