// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'api.dart';
import 'cloud_sync_chat_identity.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `failure`, `keyed_hash`, `selected_message_parent`

/// Derive a keyed physical record locator using only cached same-container
/// identity and PCS. Callers must separately prove the selected source is still
/// the current durable child and target generation before using this observation.
Future<CloudSyncDependencyParentResult> cloudSyncLocateProtectedMessageParent({
  required ArcCloudMessagesClientDefaultAnisetteProvider cloudMessagesClient,
  required BigInt nativeWriterPauseToken,
  required String storageDirectory,
  required CloudSyncNativeAuthMetadata expectedAuth,
  required String sourceZone,
  required BigInt sourceGeneration,
  required BigInt messageGeneration,
  required String expectedParentLogicalKeyHash,
  required CloudSyncChatIdentitySourceInput source,
}) => RustLib.instance.api
    .crateApiCloudSyncDependencyCloudSyncLocateProtectedMessageParent(
      cloudMessagesClient: cloudMessagesClient,
      nativeWriterPauseToken: nativeWriterPauseToken,
      storageDirectory: storageDirectory,
      expectedAuth: expectedAuth,
      sourceZone: sourceZone,
      sourceGeneration: sourceGeneration,
      messageGeneration: messageGeneration,
      expectedParentLogicalKeyHash: expectedParentLogicalKeyHash,
      source: source,
    );

class CloudSyncDependencyParentResult {
  final CloudSyncDependencyParentTarget? target;
  final CloudSyncTransientFailureCode? failureCode;

  const CloudSyncDependencyParentResult({this.target, this.failureCode});

  @override
  int get hashCode => target.hashCode ^ failureCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloudSyncDependencyParentResult &&
          runtimeType == other.runtimeType &&
          target == other.target &&
          failureCode == other.failureCode;
}

/// Diagnostic locator only. Even a complete target is not an absent-record,
/// ownership, mutation, or remote-head proof. Raw parent IDs and salt stay native.
class CloudSyncDependencyParentTarget {
  final String sourceChangeIdHash;
  final String sourceRecordIdHash;
  final BigInt sourceGeneration;
  final BigInt messageGeneration;
  final String parentLogicalKeyHash;
  final String parentRecordIdHash;
  final String nativeSessionId;
  final String bindingHash;

  const CloudSyncDependencyParentTarget({
    required this.sourceChangeIdHash,
    required this.sourceRecordIdHash,
    required this.sourceGeneration,
    required this.messageGeneration,
    required this.parentLogicalKeyHash,
    required this.parentRecordIdHash,
    required this.nativeSessionId,
    required this.bindingHash,
  });

  @override
  int get hashCode =>
      sourceChangeIdHash.hashCode ^
      sourceRecordIdHash.hashCode ^
      sourceGeneration.hashCode ^
      messageGeneration.hashCode ^
      parentLogicalKeyHash.hashCode ^
      parentRecordIdHash.hashCode ^
      nativeSessionId.hashCode ^
      bindingHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloudSyncDependencyParentTarget &&
          runtimeType == other.runtimeType &&
          sourceChangeIdHash == other.sourceChangeIdHash &&
          sourceRecordIdHash == other.sourceRecordIdHash &&
          sourceGeneration == other.sourceGeneration &&
          messageGeneration == other.messageGeneration &&
          parentLogicalKeyHash == other.parentLogicalKeyHash &&
          parentRecordIdHash == other.parentRecordIdHash &&
          nativeSessionId == other.nativeSessionId &&
          bindingHash == other.bindingHash;
}
