// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'api.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `failure`, `valid_read_set_fence`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `eq`, `fmt`

/// No keychain synchronization, remote lookup/save/delete, local projection or
/// admission. Requires a warmed exact Chat zone under an active writer pause.
/// A retained malformed record fails closed, never becomes disjoint by default.
Future<CloudSyncChatIdentityResult> cloudSyncObserveProtectedChatIdentity({
  required ArcCloudMessagesClientDefaultAnisetteProvider cloudMessagesClient,
  required BigInt nativeWriterPauseToken,
  required String storageDirectory,
  required String expectedAccountFingerprint,
  required String expectedProtectedStoreIdentity,
  required BigInt generation,
  required String readSetFenceSha256,
  required CloudChat candidate,
  required CloudSyncChatIdentitySourceInput source,
}) => RustLib.instance.api
    .crateApiCloudSyncChatIdentityCloudSyncObserveProtectedChatIdentity(
      cloudMessagesClient: cloudMessagesClient,
      nativeWriterPauseToken: nativeWriterPauseToken,
      storageDirectory: storageDirectory,
      expectedAccountFingerprint: expectedAccountFingerprint,
      expectedProtectedStoreIdentity: expectedProtectedStoreIdentity,
      generation: generation,
      readSetFenceSha256: readSetFenceSha256,
      candidate: candidate,
      source: source,
    );

enum CloudSyncChatIdentityComparison { overlaps, disjoint, incomplete }

/// Ephemeral observation only. The keyed binding covers the exact candidate,
/// source revision, caller's read-set fence and native client/store/account.
/// It does not prove the caller's read-set complete or the remote head current.
class CloudSyncChatIdentityResult {
  final CloudSyncChatIdentityComparison? comparison;
  final String? candidateBindingHash;
  final String? sourceBindingHash;
  final String? nativeSessionId;
  final CloudSyncTransientFailureCode? failureCode;

  const CloudSyncChatIdentityResult({
    this.comparison,
    this.candidateBindingHash,
    this.sourceBindingHash,
    this.nativeSessionId,
    this.failureCode,
  });

  @override
  int get hashCode =>
      comparison.hashCode ^
      candidateBindingHash.hashCode ^
      sourceBindingHash.hashCode ^
      nativeSessionId.hashCode ^
      failureCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloudSyncChatIdentityResult &&
          runtimeType == other.runtimeType &&
          comparison == other.comparison &&
          candidateBindingHash == other.candidateBindingHash &&
          sourceBindingHash == other.sourceBindingHash &&
          nativeSessionId == other.nativeSessionId &&
          failureCode == other.failureCode;
}

/// Only copied, opaque journal source metadata. Never a native record body.
class CloudSyncChatIdentitySourceInput {
  final String changeIdHash;
  final String recordIdHash;
  final String etagHash;
  final String payloadSha256;
  final BigInt? payloadLength;
  final PlatformInt64? serverModifiedAtMillis;
  final String protectedRawEnvelopeReference;

  const CloudSyncChatIdentitySourceInput({
    required this.changeIdHash,
    required this.recordIdHash,
    required this.etagHash,
    required this.payloadSha256,
    this.payloadLength,
    this.serverModifiedAtMillis,
    required this.protectedRawEnvelopeReference,
  });

  @override
  int get hashCode =>
      changeIdHash.hashCode ^
      recordIdHash.hashCode ^
      etagHash.hashCode ^
      payloadSha256.hashCode ^
      payloadLength.hashCode ^
      serverModifiedAtMillis.hashCode ^
      protectedRawEnvelopeReference.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloudSyncChatIdentitySourceInput &&
          runtimeType == other.runtimeType &&
          changeIdHash == other.changeIdHash &&
          recordIdHash == other.recordIdHash &&
          etagHash == other.etagHash &&
          payloadSha256 == other.payloadSha256 &&
          payloadLength == other.payloadLength &&
          serverModifiedAtMillis == other.serverModifiedAtMillis &&
          protectedRawEnvelopeReference == other.protectedRawEnvelopeReference;
}
