// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `classify_lah_validation_detail`, `classify_ptcpts_wire_shape_detail`, `combined`, `decode_verified_chat1_record`, `encrypted_i64_field`, `encrypted_legacy_identifiers`, `encrypted_participant_uris`, `encrypted_string_field`, `exact_match_counts`, `failure`, `inspect_chat1_route_fields_with_key`, `inspect_chat1_route_fields`, `is_bare_digest`, `is_hex_digest`, `is_protected_reference`, `matrix_index`, `message_decode_request`, `msgproto_combined`, `msgproto_pairs`, `multi_normalized_optional_target_mask`, `multi_normalized_target_mask`, `multi_optional_target_mask`, `multi_target_mask`, `new`, `normalized_combined`, `normalized_msgproto_combined`, `normalized_msgproto_pairs`, `normalized_optional_target_mask`, `normalized_pairs`, `normalized_route_extra_combined`, `normalized_route_extra_pairs`, `normalized_route_target`, `normalized_sender_combined`, `normalized_sender_pairs`, `normalized_target_mask`, `observe_route_field_failure`, `observe`, `optional_target_mask`, `paged_semantic_failure`, `pairs`, `record_identifier_name`, `record_type_name`, `route_extra_combined`, `route_extra_pairs`, `route_field_failure_matrix_snapshot`, `scan_chat1_route_pages`, `semantic_failure`, `sender_combined`, `sender_pairs`, `target_mask`, `unique_field_value`, `valid_source`, `valid_sources`, `verified_chat1_record`, `with_detail`
// These types are ignored because they are not used by any `pub` functions: `Chat1RouteFailureDetail`, `Chat1RouteFailureField`, `Chat1RouteFailureKind`, `Chat1RouteFieldFailure`, `MatchCounts`, `NormalizedRouteTarget`, `PagedSemanticCounts`, `RouteFieldMatches`, `SemanticMatchCounts`, `VerifiedChat1Record`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`, `default`, `default`

/// Performs one bounded comparison under the exact active native writer pause.
/// The default path is cached-only. A separately gated semantic diagnostic may
/// resolve the existing Chat1 PCS configuration with lookup-only reads, then
/// decrypt only selective routing strings (cid/gid/ogid/guid/lah/svc/stl and
/// participant URIs plus prop legacy identifiers). Neither path persists a
/// token, projects, admits, saves, deletes, synchronizes keychain state, or
/// repairs identity.
Future<CloudSyncChat1CorrelationResult>
cloudSyncInspectChat1RecordNameCorrelationUnderWriterPause({
  required ArcCloudMessagesClientDefaultAnisetteProvider cloudMessagesClient,
  required BigInt nativeWriterPauseToken,
  required String storageDirectory,
  required String expectedAccountFingerprint,
  required String expectedProtectedStoreIdentity,
  required BigInt messageGeneration,
  required List<CloudSyncChat1CorrelationSourceInput> messageSources,
  required BigInt chat1Generation,
  required List<CloudSyncChat1CorrelationSourceInput> chat1Sources,
}) => RustLib.instance.api
    .crateApiCloudSyncChat1CorrelationCloudSyncInspectChat1RecordNameCorrelationUnderWriterPause(
      cloudMessagesClient: cloudMessagesClient,
      nativeWriterPauseToken: nativeWriterPauseToken,
      storageDirectory: storageDirectory,
      expectedAccountFingerprint: expectedAccountFingerprint,
      expectedProtectedStoreIdentity: expectedProtectedStoreIdentity,
      messageGeneration: messageGeneration,
      messageSources: messageSources,
      chat1Generation: chat1Generation,
      chat1Sources: chat1Sources,
    );

/// Fixed failure vocabulary. No wrapped native error or account data leaves
/// this diagnostic boundary.
enum CloudSyncChat1CorrelationFailureCode {
  testHostRequired,
  invalidRequest,
  readAuthenticationScope,
  activeAccountMismatch,
  protectorUnavailable,
  messageSourceMismatch,
  messageDecodeFailed,
  chat1SourceMismatch,
  chat1PcsLookupFailed,
  chat1PagedFetchFailed,
  accountChanged,
}

/// Aggregate-only result. Exact-match fields compare a decoded Message route
/// with a verified Chat1 record name. Semantic-match fields compare its HMAC
/// with four decrypted Chat1 routing fields. Selective fields additionally
/// compare route targets with participant URIs, legacy identifiers and
/// last-addressed handle; msgProto4 group targets with cid/gid/ogid/guid and
/// legacy; and sender targets with participants and last-addressed handle.
/// Service and style are counted only as presence aggregates. Neither result
/// authorizes Chat admission, and zero never proves deletion or absence.
class CloudSyncChat1CorrelationResult {
  /// True when the requested bounded diagnostic returned normally. For a
  /// paged request this does not mean the whole zone was exhausted; callers
  /// must also inspect `paged_terminal_reached` and `paged_budget_exhausted`.
  final bool completed;
  final int messageSources;
  final int decodedMessageRoutes;
  final int distinctMessageRoutes;
  final int messageGroupIdSources;
  final int messageSenderSources;
  final int chat1Sources;
  final int verifiedChat1Records;
  final int exactMatchPairs;
  final int matchedMessageRoutes;
  final int matchedChat1Records;
  final bool semanticCorrelationRequested;
  final bool pcsLookupAttempted;
  final int chatRecordTypeRecords;
  final int otherRecordTypeRecords;
  final int decodedRouteRecords;
  final int recordDecodeFailures;
  final int routeFieldDecodeFailures;

  /// Versioned, row-major aggregate counters. Rows are record_key, cid,
  /// gid, ogid, guid, lah, svc, stl, ptcpts, prop and cross_field. Columns
  /// are missing_value, wire_shape, key_selection, ciphertext_key, decrypt,
  /// payload_decode, validation and cap. Schema 2 preserves those first 88
  /// cells exactly, then appends the fixed LAH-validation and PTCPTS-shape
  /// detail taxonomy declared by `Chat1RouteFailureDetail`.
  final int routeFieldFailureMatrixSchema;
  final Uint32List routeFieldFailureMatrix;
  final int chatIdentifierMatchPairs;
  final int groupIdMatchPairs;
  final int originalGroupIdMatchPairs;
  final int guidMatchPairs;
  final int semanticMatchPairs;
  final int matchedSemanticMessageRoutes;
  final int matchedSemanticChat1Records;
  final int routeParticipantMatchPairs;
  final int routeLegacyMatchPairs;
  final int routeLahMatchPairs;
  final int msgprotoChatIdentifierMatchPairs;
  final int msgprotoGroupIdMatchPairs;
  final int msgprotoOriginalGroupIdMatchPairs;
  final int msgprotoGuidMatchPairs;
  final int msgprotoLegacyMatchPairs;
  final int senderParticipantMatchPairs;
  final int senderLahMatchPairs;
  final int matchedRouteExtraMessageRoutes;
  final int matchedRouteExtraChat1Records;
  final int matchedMsgprotoTargets;
  final int matchedMsgprotoChat1Records;
  final int matchedSenderTargets;
  final int matchedSenderChat1Records;
  final int participantPresentRecords;
  final int legacyPresentRecords;
  final int lahPresentRecords;
  final int servicePresentRecords;
  final int imessageServiceRecords;
  final int otherServiceRecords;
  final int styleGroupRecords;
  final int styleDirectRecords;
  final int styleOtherRecords;
  final bool pagedCorrelationRequested;
  final int pagedPagesScanned;
  final int pagedChangesScanned;
  final int pagedChatRecords;
  final int pagedOtherRecords;
  final int pagedTombstones;
  final int pagedRecordDecodeFailures;
  final int pagedRouteFieldDecodeFailures;
  final Uint32List pagedRouteFieldFailureMatrix;
  final int pagedSemanticMatchPairs;
  final int pagedMatchedMessageRoutes;
  final int pagedMatchedChat1Records;
  final int pagedRouteParticipantMatchPairs;
  final int pagedRouteLegacyMatchPairs;
  final int pagedRouteLahMatchPairs;
  final int pagedMsgprotoChatIdentifierMatchPairs;
  final int pagedMsgprotoGroupIdMatchPairs;
  final int pagedMsgprotoOriginalGroupIdMatchPairs;
  final int pagedMsgprotoGuidMatchPairs;
  final int pagedMsgprotoLegacyMatchPairs;
  final int pagedSenderParticipantMatchPairs;
  final int pagedSenderLahMatchPairs;
  final int pagedMatchedRouteExtraMessageRoutes;
  final int pagedMatchedRouteExtraChat1Records;
  final int pagedMatchedMsgprotoTargets;
  final int pagedMatchedMsgprotoChat1Records;
  final int pagedMatchedSenderTargets;
  final int pagedMatchedSenderChat1Records;
  final int pagedParticipantPresentRecords;
  final int pagedLegacyPresentRecords;
  final int pagedLahPresentRecords;
  final int pagedServicePresentRecords;
  final int pagedImessageServiceRecords;
  final int pagedOtherServiceRecords;
  final int pagedStyleGroupRecords;
  final int pagedStyleDirectRecords;
  final int pagedStyleOtherRecords;
  final int pagedNormalizedChatIdentifierMatchPairs;
  final int pagedNormalizedGroupIdMatchPairs;
  final int pagedNormalizedOriginalGroupIdMatchPairs;
  final int pagedNormalizedGuidMatchPairs;
  final int pagedNormalizedSemanticMatchPairs;
  final int pagedNormalizedMatchedMessageRoutes;
  final int pagedNormalizedMatchedChat1Records;
  final int pagedNormalizedRouteParticipantMatchPairs;
  final int pagedNormalizedRouteLegacyMatchPairs;
  final int pagedNormalizedRouteLahMatchPairs;
  final int pagedNormalizedMsgprotoChatIdentifierMatchPairs;
  final int pagedNormalizedMsgprotoGroupIdMatchPairs;
  final int pagedNormalizedMsgprotoOriginalGroupIdMatchPairs;
  final int pagedNormalizedMsgprotoGuidMatchPairs;
  final int pagedNormalizedMsgprotoLegacyMatchPairs;
  final int pagedNormalizedSenderParticipantMatchPairs;
  final int pagedNormalizedSenderLahMatchPairs;
  final int pagedNormalizedMatchedRouteExtraMessageRoutes;
  final int pagedNormalizedMatchedRouteExtraChat1Records;
  final int pagedNormalizedMatchedMsgprotoTargets;
  final int pagedNormalizedMatchedMsgprotoChat1Records;
  final int pagedNormalizedMatchedSenderTargets;
  final int pagedNormalizedMatchedSenderChat1Records;
  final bool pagedTerminalReached;
  final bool pagedBudgetExhausted;
  final CloudSyncChat1CorrelationFailureCode? failureCode;

  const CloudSyncChat1CorrelationResult({
    required this.completed,
    required this.messageSources,
    required this.decodedMessageRoutes,
    required this.distinctMessageRoutes,
    required this.messageGroupIdSources,
    required this.messageSenderSources,
    required this.chat1Sources,
    required this.verifiedChat1Records,
    required this.exactMatchPairs,
    required this.matchedMessageRoutes,
    required this.matchedChat1Records,
    required this.semanticCorrelationRequested,
    required this.pcsLookupAttempted,
    required this.chatRecordTypeRecords,
    required this.otherRecordTypeRecords,
    required this.decodedRouteRecords,
    required this.recordDecodeFailures,
    required this.routeFieldDecodeFailures,
    required this.routeFieldFailureMatrixSchema,
    required this.routeFieldFailureMatrix,
    required this.chatIdentifierMatchPairs,
    required this.groupIdMatchPairs,
    required this.originalGroupIdMatchPairs,
    required this.guidMatchPairs,
    required this.semanticMatchPairs,
    required this.matchedSemanticMessageRoutes,
    required this.matchedSemanticChat1Records,
    required this.routeParticipantMatchPairs,
    required this.routeLegacyMatchPairs,
    required this.routeLahMatchPairs,
    required this.msgprotoChatIdentifierMatchPairs,
    required this.msgprotoGroupIdMatchPairs,
    required this.msgprotoOriginalGroupIdMatchPairs,
    required this.msgprotoGuidMatchPairs,
    required this.msgprotoLegacyMatchPairs,
    required this.senderParticipantMatchPairs,
    required this.senderLahMatchPairs,
    required this.matchedRouteExtraMessageRoutes,
    required this.matchedRouteExtraChat1Records,
    required this.matchedMsgprotoTargets,
    required this.matchedMsgprotoChat1Records,
    required this.matchedSenderTargets,
    required this.matchedSenderChat1Records,
    required this.participantPresentRecords,
    required this.legacyPresentRecords,
    required this.lahPresentRecords,
    required this.servicePresentRecords,
    required this.imessageServiceRecords,
    required this.otherServiceRecords,
    required this.styleGroupRecords,
    required this.styleDirectRecords,
    required this.styleOtherRecords,
    required this.pagedCorrelationRequested,
    required this.pagedPagesScanned,
    required this.pagedChangesScanned,
    required this.pagedChatRecords,
    required this.pagedOtherRecords,
    required this.pagedTombstones,
    required this.pagedRecordDecodeFailures,
    required this.pagedRouteFieldDecodeFailures,
    required this.pagedRouteFieldFailureMatrix,
    required this.pagedSemanticMatchPairs,
    required this.pagedMatchedMessageRoutes,
    required this.pagedMatchedChat1Records,
    required this.pagedRouteParticipantMatchPairs,
    required this.pagedRouteLegacyMatchPairs,
    required this.pagedRouteLahMatchPairs,
    required this.pagedMsgprotoChatIdentifierMatchPairs,
    required this.pagedMsgprotoGroupIdMatchPairs,
    required this.pagedMsgprotoOriginalGroupIdMatchPairs,
    required this.pagedMsgprotoGuidMatchPairs,
    required this.pagedMsgprotoLegacyMatchPairs,
    required this.pagedSenderParticipantMatchPairs,
    required this.pagedSenderLahMatchPairs,
    required this.pagedMatchedRouteExtraMessageRoutes,
    required this.pagedMatchedRouteExtraChat1Records,
    required this.pagedMatchedMsgprotoTargets,
    required this.pagedMatchedMsgprotoChat1Records,
    required this.pagedMatchedSenderTargets,
    required this.pagedMatchedSenderChat1Records,
    required this.pagedParticipantPresentRecords,
    required this.pagedLegacyPresentRecords,
    required this.pagedLahPresentRecords,
    required this.pagedServicePresentRecords,
    required this.pagedImessageServiceRecords,
    required this.pagedOtherServiceRecords,
    required this.pagedStyleGroupRecords,
    required this.pagedStyleDirectRecords,
    required this.pagedStyleOtherRecords,
    required this.pagedNormalizedChatIdentifierMatchPairs,
    required this.pagedNormalizedGroupIdMatchPairs,
    required this.pagedNormalizedOriginalGroupIdMatchPairs,
    required this.pagedNormalizedGuidMatchPairs,
    required this.pagedNormalizedSemanticMatchPairs,
    required this.pagedNormalizedMatchedMessageRoutes,
    required this.pagedNormalizedMatchedChat1Records,
    required this.pagedNormalizedRouteParticipantMatchPairs,
    required this.pagedNormalizedRouteLegacyMatchPairs,
    required this.pagedNormalizedRouteLahMatchPairs,
    required this.pagedNormalizedMsgprotoChatIdentifierMatchPairs,
    required this.pagedNormalizedMsgprotoGroupIdMatchPairs,
    required this.pagedNormalizedMsgprotoOriginalGroupIdMatchPairs,
    required this.pagedNormalizedMsgprotoGuidMatchPairs,
    required this.pagedNormalizedMsgprotoLegacyMatchPairs,
    required this.pagedNormalizedSenderParticipantMatchPairs,
    required this.pagedNormalizedSenderLahMatchPairs,
    required this.pagedNormalizedMatchedRouteExtraMessageRoutes,
    required this.pagedNormalizedMatchedRouteExtraChat1Records,
    required this.pagedNormalizedMatchedMsgprotoTargets,
    required this.pagedNormalizedMatchedMsgprotoChat1Records,
    required this.pagedNormalizedMatchedSenderTargets,
    required this.pagedNormalizedMatchedSenderChat1Records,
    required this.pagedTerminalReached,
    required this.pagedBudgetExhausted,
    this.failureCode,
  });

  @override
  int get hashCode =>
      completed.hashCode ^
      messageSources.hashCode ^
      decodedMessageRoutes.hashCode ^
      distinctMessageRoutes.hashCode ^
      messageGroupIdSources.hashCode ^
      messageSenderSources.hashCode ^
      chat1Sources.hashCode ^
      verifiedChat1Records.hashCode ^
      exactMatchPairs.hashCode ^
      matchedMessageRoutes.hashCode ^
      matchedChat1Records.hashCode ^
      semanticCorrelationRequested.hashCode ^
      pcsLookupAttempted.hashCode ^
      chatRecordTypeRecords.hashCode ^
      otherRecordTypeRecords.hashCode ^
      decodedRouteRecords.hashCode ^
      recordDecodeFailures.hashCode ^
      routeFieldDecodeFailures.hashCode ^
      routeFieldFailureMatrixSchema.hashCode ^
      routeFieldFailureMatrix.hashCode ^
      chatIdentifierMatchPairs.hashCode ^
      groupIdMatchPairs.hashCode ^
      originalGroupIdMatchPairs.hashCode ^
      guidMatchPairs.hashCode ^
      semanticMatchPairs.hashCode ^
      matchedSemanticMessageRoutes.hashCode ^
      matchedSemanticChat1Records.hashCode ^
      routeParticipantMatchPairs.hashCode ^
      routeLegacyMatchPairs.hashCode ^
      routeLahMatchPairs.hashCode ^
      msgprotoChatIdentifierMatchPairs.hashCode ^
      msgprotoGroupIdMatchPairs.hashCode ^
      msgprotoOriginalGroupIdMatchPairs.hashCode ^
      msgprotoGuidMatchPairs.hashCode ^
      msgprotoLegacyMatchPairs.hashCode ^
      senderParticipantMatchPairs.hashCode ^
      senderLahMatchPairs.hashCode ^
      matchedRouteExtraMessageRoutes.hashCode ^
      matchedRouteExtraChat1Records.hashCode ^
      matchedMsgprotoTargets.hashCode ^
      matchedMsgprotoChat1Records.hashCode ^
      matchedSenderTargets.hashCode ^
      matchedSenderChat1Records.hashCode ^
      participantPresentRecords.hashCode ^
      legacyPresentRecords.hashCode ^
      lahPresentRecords.hashCode ^
      servicePresentRecords.hashCode ^
      imessageServiceRecords.hashCode ^
      otherServiceRecords.hashCode ^
      styleGroupRecords.hashCode ^
      styleDirectRecords.hashCode ^
      styleOtherRecords.hashCode ^
      pagedCorrelationRequested.hashCode ^
      pagedPagesScanned.hashCode ^
      pagedChangesScanned.hashCode ^
      pagedChatRecords.hashCode ^
      pagedOtherRecords.hashCode ^
      pagedTombstones.hashCode ^
      pagedRecordDecodeFailures.hashCode ^
      pagedRouteFieldDecodeFailures.hashCode ^
      pagedRouteFieldFailureMatrix.hashCode ^
      pagedSemanticMatchPairs.hashCode ^
      pagedMatchedMessageRoutes.hashCode ^
      pagedMatchedChat1Records.hashCode ^
      pagedRouteParticipantMatchPairs.hashCode ^
      pagedRouteLegacyMatchPairs.hashCode ^
      pagedRouteLahMatchPairs.hashCode ^
      pagedMsgprotoChatIdentifierMatchPairs.hashCode ^
      pagedMsgprotoGroupIdMatchPairs.hashCode ^
      pagedMsgprotoOriginalGroupIdMatchPairs.hashCode ^
      pagedMsgprotoGuidMatchPairs.hashCode ^
      pagedMsgprotoLegacyMatchPairs.hashCode ^
      pagedSenderParticipantMatchPairs.hashCode ^
      pagedSenderLahMatchPairs.hashCode ^
      pagedMatchedRouteExtraMessageRoutes.hashCode ^
      pagedMatchedRouteExtraChat1Records.hashCode ^
      pagedMatchedMsgprotoTargets.hashCode ^
      pagedMatchedMsgprotoChat1Records.hashCode ^
      pagedMatchedSenderTargets.hashCode ^
      pagedMatchedSenderChat1Records.hashCode ^
      pagedParticipantPresentRecords.hashCode ^
      pagedLegacyPresentRecords.hashCode ^
      pagedLahPresentRecords.hashCode ^
      pagedServicePresentRecords.hashCode ^
      pagedImessageServiceRecords.hashCode ^
      pagedOtherServiceRecords.hashCode ^
      pagedStyleGroupRecords.hashCode ^
      pagedStyleDirectRecords.hashCode ^
      pagedStyleOtherRecords.hashCode ^
      pagedNormalizedChatIdentifierMatchPairs.hashCode ^
      pagedNormalizedGroupIdMatchPairs.hashCode ^
      pagedNormalizedOriginalGroupIdMatchPairs.hashCode ^
      pagedNormalizedGuidMatchPairs.hashCode ^
      pagedNormalizedSemanticMatchPairs.hashCode ^
      pagedNormalizedMatchedMessageRoutes.hashCode ^
      pagedNormalizedMatchedChat1Records.hashCode ^
      pagedNormalizedRouteParticipantMatchPairs.hashCode ^
      pagedNormalizedRouteLegacyMatchPairs.hashCode ^
      pagedNormalizedRouteLahMatchPairs.hashCode ^
      pagedNormalizedMsgprotoChatIdentifierMatchPairs.hashCode ^
      pagedNormalizedMsgprotoGroupIdMatchPairs.hashCode ^
      pagedNormalizedMsgprotoOriginalGroupIdMatchPairs.hashCode ^
      pagedNormalizedMsgprotoGuidMatchPairs.hashCode ^
      pagedNormalizedMsgprotoLegacyMatchPairs.hashCode ^
      pagedNormalizedSenderParticipantMatchPairs.hashCode ^
      pagedNormalizedSenderLahMatchPairs.hashCode ^
      pagedNormalizedMatchedRouteExtraMessageRoutes.hashCode ^
      pagedNormalizedMatchedRouteExtraChat1Records.hashCode ^
      pagedNormalizedMatchedMsgprotoTargets.hashCode ^
      pagedNormalizedMatchedMsgprotoChat1Records.hashCode ^
      pagedNormalizedMatchedSenderTargets.hashCode ^
      pagedNormalizedMatchedSenderChat1Records.hashCode ^
      pagedTerminalReached.hashCode ^
      pagedBudgetExhausted.hashCode ^
      failureCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloudSyncChat1CorrelationResult &&
          runtimeType == other.runtimeType &&
          completed == other.completed &&
          messageSources == other.messageSources &&
          decodedMessageRoutes == other.decodedMessageRoutes &&
          distinctMessageRoutes == other.distinctMessageRoutes &&
          messageGroupIdSources == other.messageGroupIdSources &&
          messageSenderSources == other.messageSenderSources &&
          chat1Sources == other.chat1Sources &&
          verifiedChat1Records == other.verifiedChat1Records &&
          exactMatchPairs == other.exactMatchPairs &&
          matchedMessageRoutes == other.matchedMessageRoutes &&
          matchedChat1Records == other.matchedChat1Records &&
          semanticCorrelationRequested == other.semanticCorrelationRequested &&
          pcsLookupAttempted == other.pcsLookupAttempted &&
          chatRecordTypeRecords == other.chatRecordTypeRecords &&
          otherRecordTypeRecords == other.otherRecordTypeRecords &&
          decodedRouteRecords == other.decodedRouteRecords &&
          recordDecodeFailures == other.recordDecodeFailures &&
          routeFieldDecodeFailures == other.routeFieldDecodeFailures &&
          routeFieldFailureMatrixSchema ==
              other.routeFieldFailureMatrixSchema &&
          routeFieldFailureMatrix == other.routeFieldFailureMatrix &&
          chatIdentifierMatchPairs == other.chatIdentifierMatchPairs &&
          groupIdMatchPairs == other.groupIdMatchPairs &&
          originalGroupIdMatchPairs == other.originalGroupIdMatchPairs &&
          guidMatchPairs == other.guidMatchPairs &&
          semanticMatchPairs == other.semanticMatchPairs &&
          matchedSemanticMessageRoutes == other.matchedSemanticMessageRoutes &&
          matchedSemanticChat1Records == other.matchedSemanticChat1Records &&
          routeParticipantMatchPairs == other.routeParticipantMatchPairs &&
          routeLegacyMatchPairs == other.routeLegacyMatchPairs &&
          routeLahMatchPairs == other.routeLahMatchPairs &&
          msgprotoChatIdentifierMatchPairs ==
              other.msgprotoChatIdentifierMatchPairs &&
          msgprotoGroupIdMatchPairs == other.msgprotoGroupIdMatchPairs &&
          msgprotoOriginalGroupIdMatchPairs ==
              other.msgprotoOriginalGroupIdMatchPairs &&
          msgprotoGuidMatchPairs == other.msgprotoGuidMatchPairs &&
          msgprotoLegacyMatchPairs == other.msgprotoLegacyMatchPairs &&
          senderParticipantMatchPairs == other.senderParticipantMatchPairs &&
          senderLahMatchPairs == other.senderLahMatchPairs &&
          matchedRouteExtraMessageRoutes ==
              other.matchedRouteExtraMessageRoutes &&
          matchedRouteExtraChat1Records ==
              other.matchedRouteExtraChat1Records &&
          matchedMsgprotoTargets == other.matchedMsgprotoTargets &&
          matchedMsgprotoChat1Records == other.matchedMsgprotoChat1Records &&
          matchedSenderTargets == other.matchedSenderTargets &&
          matchedSenderChat1Records == other.matchedSenderChat1Records &&
          participantPresentRecords == other.participantPresentRecords &&
          legacyPresentRecords == other.legacyPresentRecords &&
          lahPresentRecords == other.lahPresentRecords &&
          servicePresentRecords == other.servicePresentRecords &&
          imessageServiceRecords == other.imessageServiceRecords &&
          otherServiceRecords == other.otherServiceRecords &&
          styleGroupRecords == other.styleGroupRecords &&
          styleDirectRecords == other.styleDirectRecords &&
          styleOtherRecords == other.styleOtherRecords &&
          pagedCorrelationRequested == other.pagedCorrelationRequested &&
          pagedPagesScanned == other.pagedPagesScanned &&
          pagedChangesScanned == other.pagedChangesScanned &&
          pagedChatRecords == other.pagedChatRecords &&
          pagedOtherRecords == other.pagedOtherRecords &&
          pagedTombstones == other.pagedTombstones &&
          pagedRecordDecodeFailures == other.pagedRecordDecodeFailures &&
          pagedRouteFieldDecodeFailures ==
              other.pagedRouteFieldDecodeFailures &&
          pagedRouteFieldFailureMatrix == other.pagedRouteFieldFailureMatrix &&
          pagedSemanticMatchPairs == other.pagedSemanticMatchPairs &&
          pagedMatchedMessageRoutes == other.pagedMatchedMessageRoutes &&
          pagedMatchedChat1Records == other.pagedMatchedChat1Records &&
          pagedRouteParticipantMatchPairs ==
              other.pagedRouteParticipantMatchPairs &&
          pagedRouteLegacyMatchPairs == other.pagedRouteLegacyMatchPairs &&
          pagedRouteLahMatchPairs == other.pagedRouteLahMatchPairs &&
          pagedMsgprotoChatIdentifierMatchPairs ==
              other.pagedMsgprotoChatIdentifierMatchPairs &&
          pagedMsgprotoGroupIdMatchPairs ==
              other.pagedMsgprotoGroupIdMatchPairs &&
          pagedMsgprotoOriginalGroupIdMatchPairs ==
              other.pagedMsgprotoOriginalGroupIdMatchPairs &&
          pagedMsgprotoGuidMatchPairs == other.pagedMsgprotoGuidMatchPairs &&
          pagedMsgprotoLegacyMatchPairs ==
              other.pagedMsgprotoLegacyMatchPairs &&
          pagedSenderParticipantMatchPairs ==
              other.pagedSenderParticipantMatchPairs &&
          pagedSenderLahMatchPairs == other.pagedSenderLahMatchPairs &&
          pagedMatchedRouteExtraMessageRoutes ==
              other.pagedMatchedRouteExtraMessageRoutes &&
          pagedMatchedRouteExtraChat1Records ==
              other.pagedMatchedRouteExtraChat1Records &&
          pagedMatchedMsgprotoTargets == other.pagedMatchedMsgprotoTargets &&
          pagedMatchedMsgprotoChat1Records ==
              other.pagedMatchedMsgprotoChat1Records &&
          pagedMatchedSenderTargets == other.pagedMatchedSenderTargets &&
          pagedMatchedSenderChat1Records ==
              other.pagedMatchedSenderChat1Records &&
          pagedParticipantPresentRecords ==
              other.pagedParticipantPresentRecords &&
          pagedLegacyPresentRecords == other.pagedLegacyPresentRecords &&
          pagedLahPresentRecords == other.pagedLahPresentRecords &&
          pagedServicePresentRecords == other.pagedServicePresentRecords &&
          pagedImessageServiceRecords == other.pagedImessageServiceRecords &&
          pagedOtherServiceRecords == other.pagedOtherServiceRecords &&
          pagedStyleGroupRecords == other.pagedStyleGroupRecords &&
          pagedStyleDirectRecords == other.pagedStyleDirectRecords &&
          pagedStyleOtherRecords == other.pagedStyleOtherRecords &&
          pagedNormalizedChatIdentifierMatchPairs ==
              other.pagedNormalizedChatIdentifierMatchPairs &&
          pagedNormalizedGroupIdMatchPairs ==
              other.pagedNormalizedGroupIdMatchPairs &&
          pagedNormalizedOriginalGroupIdMatchPairs ==
              other.pagedNormalizedOriginalGroupIdMatchPairs &&
          pagedNormalizedGuidMatchPairs ==
              other.pagedNormalizedGuidMatchPairs &&
          pagedNormalizedSemanticMatchPairs ==
              other.pagedNormalizedSemanticMatchPairs &&
          pagedNormalizedMatchedMessageRoutes ==
              other.pagedNormalizedMatchedMessageRoutes &&
          pagedNormalizedMatchedChat1Records ==
              other.pagedNormalizedMatchedChat1Records &&
          pagedNormalizedRouteParticipantMatchPairs ==
              other.pagedNormalizedRouteParticipantMatchPairs &&
          pagedNormalizedRouteLegacyMatchPairs ==
              other.pagedNormalizedRouteLegacyMatchPairs &&
          pagedNormalizedRouteLahMatchPairs ==
              other.pagedNormalizedRouteLahMatchPairs &&
          pagedNormalizedMsgprotoChatIdentifierMatchPairs ==
              other.pagedNormalizedMsgprotoChatIdentifierMatchPairs &&
          pagedNormalizedMsgprotoGroupIdMatchPairs ==
              other.pagedNormalizedMsgprotoGroupIdMatchPairs &&
          pagedNormalizedMsgprotoOriginalGroupIdMatchPairs ==
              other.pagedNormalizedMsgprotoOriginalGroupIdMatchPairs &&
          pagedNormalizedMsgprotoGuidMatchPairs ==
              other.pagedNormalizedMsgprotoGuidMatchPairs &&
          pagedNormalizedMsgprotoLegacyMatchPairs ==
              other.pagedNormalizedMsgprotoLegacyMatchPairs &&
          pagedNormalizedSenderParticipantMatchPairs ==
              other.pagedNormalizedSenderParticipantMatchPairs &&
          pagedNormalizedSenderLahMatchPairs ==
              other.pagedNormalizedSenderLahMatchPairs &&
          pagedNormalizedMatchedRouteExtraMessageRoutes ==
              other.pagedNormalizedMatchedRouteExtraMessageRoutes &&
          pagedNormalizedMatchedRouteExtraChat1Records ==
              other.pagedNormalizedMatchedRouteExtraChat1Records &&
          pagedNormalizedMatchedMsgprotoTargets ==
              other.pagedNormalizedMatchedMsgprotoTargets &&
          pagedNormalizedMatchedMsgprotoChat1Records ==
              other.pagedNormalizedMatchedMsgprotoChat1Records &&
          pagedNormalizedMatchedSenderTargets ==
              other.pagedNormalizedMatchedSenderTargets &&
          pagedNormalizedMatchedSenderChat1Records ==
              other.pagedNormalizedMatchedSenderChat1Records &&
          pagedTerminalReached == other.pagedTerminalReached &&
          pagedBudgetExhausted == other.pagedBudgetExhausted &&
          failureCode == other.failureCode;
}

/// Exact opaque metadata copied from one already-adopted journal row. No raw
/// record name, route, field value, Apple token, or message body is present.
class CloudSyncChat1CorrelationSourceInput {
  final String changeIdHash;
  final String recordIdHash;
  final String? etagHash;
  final String payloadSha256;
  final BigInt? payloadLength;
  final PlatformInt64? serverModifiedAtMillis;
  final String protectedRawEnvelopeReference;

  const CloudSyncChat1CorrelationSourceInput({
    required this.changeIdHash,
    required this.recordIdHash,
    this.etagHash,
    required this.payloadSha256,
    this.payloadLength,
    this.serverModifiedAtMillis,
    required this.protectedRawEnvelopeReference,
  });

  @override
  int get hashCode =>
      changeIdHash.hashCode ^
      recordIdHash.hashCode ^
      etagHash.hashCode ^
      payloadSha256.hashCode ^
      payloadLength.hashCode ^
      serverModifiedAtMillis.hashCode ^
      protectedRawEnvelopeReference.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloudSyncChat1CorrelationSourceInput &&
          runtimeType == other.runtimeType &&
          changeIdHash == other.changeIdHash &&
          recordIdHash == other.recordIdHash &&
          etagHash == other.etagHash &&
          payloadSha256 == other.payloadSha256 &&
          payloadLength == other.payloadLength &&
          serverModifiedAtMillis == other.serverModifiedAtMillis &&
          protectedRawEnvelopeReference == other.protectedRawEnvelopeReference;
}
