// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `combined`, `decode_verified_chat1_record`, `encrypted_string_field`, `exact_match_counts`, `failure`, `inspect_chat1_route_fields`, `is_bare_digest`, `is_hex_digest`, `is_protected_reference`, `message_decode_request`, `normalized_combined`, `normalized_pairs`, `normalized_route_target`, `normalized_target_mask`, `observe`, `paged_semantic_failure`, `pairs`, `record_identifier_name`, `record_type_name`, `scan_chat1_route_pages`, `semantic_failure`, `target_mask`, `valid_source`, `valid_sources`, `verified_chat1_record`
// These types are ignored because they are not used by any `pub` functions: `MatchCounts`, `NormalizedRouteTarget`, `PagedSemanticCounts`, `RouteFieldMatches`, `SemanticMatchCounts`, `VerifiedChat1Record`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`, `default`, `default`

/// Performs one bounded comparison under the exact active native writer pause.
/// The default path is cached-only. A separately gated semantic diagnostic may
/// resolve the existing Chat1 PCS configuration with lookup-only reads, then
/// decrypt only four routing strings. Neither path persists a token, projects,
/// admits, saves, deletes, synchronizes keychain state, or repairs identity.
Future<CloudSyncChat1CorrelationResult>
cloudSyncInspectChat1RecordNameCorrelationUnderWriterPause({
  required ArcCloudMessagesClientDefaultAnisetteProvider cloudMessagesClient,
  required BigInt nativeWriterPauseToken,
  required String storageDirectory,
  required String expectedAccountFingerprint,
  required String expectedProtectedStoreIdentity,
  required BigInt messageGeneration,
  required List<CloudSyncChat1CorrelationSourceInput> messageSources,
  required BigInt chat1Generation,
  required List<CloudSyncChat1CorrelationSourceInput> chat1Sources,
}) => RustLib.instance.api
    .crateApiCloudSyncChat1CorrelationCloudSyncInspectChat1RecordNameCorrelationUnderWriterPause(
      cloudMessagesClient: cloudMessagesClient,
      nativeWriterPauseToken: nativeWriterPauseToken,
      storageDirectory: storageDirectory,
      expectedAccountFingerprint: expectedAccountFingerprint,
      expectedProtectedStoreIdentity: expectedProtectedStoreIdentity,
      messageGeneration: messageGeneration,
      messageSources: messageSources,
      chat1Generation: chat1Generation,
      chat1Sources: chat1Sources,
    );

/// Fixed failure vocabulary. No wrapped native error or account data leaves
/// this diagnostic boundary.
enum CloudSyncChat1CorrelationFailureCode {
  testHostRequired,
  invalidRequest,
  readAuthenticationScope,
  activeAccountMismatch,
  protectorUnavailable,
  messageSourceMismatch,
  messageDecodeFailed,
  chat1SourceMismatch,
  chat1PcsLookupFailed,
  chat1PagedFetchFailed,
  accountChanged,
}

/// Aggregate-only result. Exact-match fields compare a decoded Message route
/// with a verified Chat1 record name. Semantic-match fields compare its HMAC
/// with four decrypted Chat1 routing fields. Neither result authorizes Chat
/// admission, and zero never proves deletion or absence.
class CloudSyncChat1CorrelationResult {
  final bool completed;
  final int messageSources;
  final int decodedMessageRoutes;
  final int distinctMessageRoutes;
  final int chat1Sources;
  final int verifiedChat1Records;
  final int exactMatchPairs;
  final int matchedMessageRoutes;
  final int matchedChat1Records;
  final bool semanticCorrelationRequested;
  final bool pcsLookupAttempted;
  final int chatRecordTypeRecords;
  final int otherRecordTypeRecords;
  final int decodedRouteRecords;
  final int recordDecodeFailures;
  final int routeFieldDecodeFailures;
  final int chatIdentifierMatchPairs;
  final int groupIdMatchPairs;
  final int originalGroupIdMatchPairs;
  final int guidMatchPairs;
  final int semanticMatchPairs;
  final int matchedSemanticMessageRoutes;
  final int matchedSemanticChat1Records;
  final bool pagedCorrelationRequested;
  final int pagedPagesScanned;
  final int pagedChangesScanned;
  final int pagedChatRecords;
  final int pagedOtherRecords;
  final int pagedTombstones;
  final int pagedRecordDecodeFailures;
  final int pagedRouteFieldDecodeFailures;
  final int pagedSemanticMatchPairs;
  final int pagedMatchedMessageRoutes;
  final int pagedMatchedChat1Records;
  final int pagedNormalizedChatIdentifierMatchPairs;
  final int pagedNormalizedGroupIdMatchPairs;
  final int pagedNormalizedOriginalGroupIdMatchPairs;
  final int pagedNormalizedGuidMatchPairs;
  final int pagedNormalizedSemanticMatchPairs;
  final int pagedNormalizedMatchedMessageRoutes;
  final int pagedNormalizedMatchedChat1Records;
  final bool pagedTerminalReached;
  final bool pagedBudgetExhausted;
  final CloudSyncChat1CorrelationFailureCode? failureCode;

  const CloudSyncChat1CorrelationResult({
    required this.completed,
    required this.messageSources,
    required this.decodedMessageRoutes,
    required this.distinctMessageRoutes,
    required this.chat1Sources,
    required this.verifiedChat1Records,
    required this.exactMatchPairs,
    required this.matchedMessageRoutes,
    required this.matchedChat1Records,
    required this.semanticCorrelationRequested,
    required this.pcsLookupAttempted,
    required this.chatRecordTypeRecords,
    required this.otherRecordTypeRecords,
    required this.decodedRouteRecords,
    required this.recordDecodeFailures,
    required this.routeFieldDecodeFailures,
    required this.chatIdentifierMatchPairs,
    required this.groupIdMatchPairs,
    required this.originalGroupIdMatchPairs,
    required this.guidMatchPairs,
    required this.semanticMatchPairs,
    required this.matchedSemanticMessageRoutes,
    required this.matchedSemanticChat1Records,
    required this.pagedCorrelationRequested,
    required this.pagedPagesScanned,
    required this.pagedChangesScanned,
    required this.pagedChatRecords,
    required this.pagedOtherRecords,
    required this.pagedTombstones,
    required this.pagedRecordDecodeFailures,
    required this.pagedRouteFieldDecodeFailures,
    required this.pagedSemanticMatchPairs,
    required this.pagedMatchedMessageRoutes,
    required this.pagedMatchedChat1Records,
    required this.pagedNormalizedChatIdentifierMatchPairs,
    required this.pagedNormalizedGroupIdMatchPairs,
    required this.pagedNormalizedOriginalGroupIdMatchPairs,
    required this.pagedNormalizedGuidMatchPairs,
    required this.pagedNormalizedSemanticMatchPairs,
    required this.pagedNormalizedMatchedMessageRoutes,
    required this.pagedNormalizedMatchedChat1Records,
    required this.pagedTerminalReached,
    required this.pagedBudgetExhausted,
    this.failureCode,
  });

  @override
  int get hashCode =>
      completed.hashCode ^
      messageSources.hashCode ^
      decodedMessageRoutes.hashCode ^
      distinctMessageRoutes.hashCode ^
      chat1Sources.hashCode ^
      verifiedChat1Records.hashCode ^
      exactMatchPairs.hashCode ^
      matchedMessageRoutes.hashCode ^
      matchedChat1Records.hashCode ^
      semanticCorrelationRequested.hashCode ^
      pcsLookupAttempted.hashCode ^
      chatRecordTypeRecords.hashCode ^
      otherRecordTypeRecords.hashCode ^
      decodedRouteRecords.hashCode ^
      recordDecodeFailures.hashCode ^
      routeFieldDecodeFailures.hashCode ^
      chatIdentifierMatchPairs.hashCode ^
      groupIdMatchPairs.hashCode ^
      originalGroupIdMatchPairs.hashCode ^
      guidMatchPairs.hashCode ^
      semanticMatchPairs.hashCode ^
      matchedSemanticMessageRoutes.hashCode ^
      matchedSemanticChat1Records.hashCode ^
      pagedCorrelationRequested.hashCode ^
      pagedPagesScanned.hashCode ^
      pagedChangesScanned.hashCode ^
      pagedChatRecords.hashCode ^
      pagedOtherRecords.hashCode ^
      pagedTombstones.hashCode ^
      pagedRecordDecodeFailures.hashCode ^
      pagedRouteFieldDecodeFailures.hashCode ^
      pagedSemanticMatchPairs.hashCode ^
      pagedMatchedMessageRoutes.hashCode ^
      pagedMatchedChat1Records.hashCode ^
      pagedNormalizedChatIdentifierMatchPairs.hashCode ^
      pagedNormalizedGroupIdMatchPairs.hashCode ^
      pagedNormalizedOriginalGroupIdMatchPairs.hashCode ^
      pagedNormalizedGuidMatchPairs.hashCode ^
      pagedNormalizedSemanticMatchPairs.hashCode ^
      pagedNormalizedMatchedMessageRoutes.hashCode ^
      pagedNormalizedMatchedChat1Records.hashCode ^
      pagedTerminalReached.hashCode ^
      pagedBudgetExhausted.hashCode ^
      failureCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloudSyncChat1CorrelationResult &&
          runtimeType == other.runtimeType &&
          completed == other.completed &&
          messageSources == other.messageSources &&
          decodedMessageRoutes == other.decodedMessageRoutes &&
          distinctMessageRoutes == other.distinctMessageRoutes &&
          chat1Sources == other.chat1Sources &&
          verifiedChat1Records == other.verifiedChat1Records &&
          exactMatchPairs == other.exactMatchPairs &&
          matchedMessageRoutes == other.matchedMessageRoutes &&
          matchedChat1Records == other.matchedChat1Records &&
          semanticCorrelationRequested == other.semanticCorrelationRequested &&
          pcsLookupAttempted == other.pcsLookupAttempted &&
          chatRecordTypeRecords == other.chatRecordTypeRecords &&
          otherRecordTypeRecords == other.otherRecordTypeRecords &&
          decodedRouteRecords == other.decodedRouteRecords &&
          recordDecodeFailures == other.recordDecodeFailures &&
          routeFieldDecodeFailures == other.routeFieldDecodeFailures &&
          chatIdentifierMatchPairs == other.chatIdentifierMatchPairs &&
          groupIdMatchPairs == other.groupIdMatchPairs &&
          originalGroupIdMatchPairs == other.originalGroupIdMatchPairs &&
          guidMatchPairs == other.guidMatchPairs &&
          semanticMatchPairs == other.semanticMatchPairs &&
          matchedSemanticMessageRoutes == other.matchedSemanticMessageRoutes &&
          matchedSemanticChat1Records == other.matchedSemanticChat1Records &&
          pagedCorrelationRequested == other.pagedCorrelationRequested &&
          pagedPagesScanned == other.pagedPagesScanned &&
          pagedChangesScanned == other.pagedChangesScanned &&
          pagedChatRecords == other.pagedChatRecords &&
          pagedOtherRecords == other.pagedOtherRecords &&
          pagedTombstones == other.pagedTombstones &&
          pagedRecordDecodeFailures == other.pagedRecordDecodeFailures &&
          pagedRouteFieldDecodeFailures ==
              other.pagedRouteFieldDecodeFailures &&
          pagedSemanticMatchPairs == other.pagedSemanticMatchPairs &&
          pagedMatchedMessageRoutes == other.pagedMatchedMessageRoutes &&
          pagedMatchedChat1Records == other.pagedMatchedChat1Records &&
          pagedNormalizedChatIdentifierMatchPairs ==
              other.pagedNormalizedChatIdentifierMatchPairs &&
          pagedNormalizedGroupIdMatchPairs ==
              other.pagedNormalizedGroupIdMatchPairs &&
          pagedNormalizedOriginalGroupIdMatchPairs ==
              other.pagedNormalizedOriginalGroupIdMatchPairs &&
          pagedNormalizedGuidMatchPairs ==
              other.pagedNormalizedGuidMatchPairs &&
          pagedNormalizedSemanticMatchPairs ==
              other.pagedNormalizedSemanticMatchPairs &&
          pagedNormalizedMatchedMessageRoutes ==
              other.pagedNormalizedMatchedMessageRoutes &&
          pagedNormalizedMatchedChat1Records ==
              other.pagedNormalizedMatchedChat1Records &&
          pagedTerminalReached == other.pagedTerminalReached &&
          pagedBudgetExhausted == other.pagedBudgetExhausted &&
          failureCode == other.failureCode;
}

/// Exact opaque metadata copied from one already-adopted journal row. No raw
/// record name, route, field value, Apple token, or message body is present.
class CloudSyncChat1CorrelationSourceInput {
  final String changeIdHash;
  final String recordIdHash;
  final String? etagHash;
  final String payloadSha256;
  final BigInt? payloadLength;
  final PlatformInt64? serverModifiedAtMillis;
  final String protectedRawEnvelopeReference;

  const CloudSyncChat1CorrelationSourceInput({
    required this.changeIdHash,
    required this.recordIdHash,
    this.etagHash,
    required this.payloadSha256,
    this.payloadLength,
    this.serverModifiedAtMillis,
    required this.protectedRawEnvelopeReference,
  });

  @override
  int get hashCode =>
      changeIdHash.hashCode ^
      recordIdHash.hashCode ^
      etagHash.hashCode ^
      payloadSha256.hashCode ^
      payloadLength.hashCode ^
      serverModifiedAtMillis.hashCode ^
      protectedRawEnvelopeReference.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloudSyncChat1CorrelationSourceInput &&
          runtimeType == other.runtimeType &&
          changeIdHash == other.changeIdHash &&
          recordIdHash == other.recordIdHash &&
          etagHash == other.etagHash &&
          payloadSha256 == other.payloadSha256 &&
          payloadLength == other.payloadLength &&
          serverModifiedAtMillis == other.serverModifiedAtMillis &&
          protectedRawEnvelopeReference == other.protectedRawEnvelopeReference;
}
